stages:
  - containerize

variables:
  DOCKER_REGISTRY: "hub.zigpos.com/dev"
  REPO_GROUP: "zpBTScanner"
  DOCKER_CLI_EXPERIMENTAL: "enabled"

Docker release arm64:
  image: hub.zigpos.com/ci/docker-ci:2022.1
  tags:
    - docker-arm64
  script:
    - "echo otha"

