stages:
  - containerize

variables:
  DOCKER_REGISTRY: "docker.zigpos.de" # for pulling docker images
  REPO_GROUP: "zp-btscanner"

amd64:
  stage: containerize
  image: docker.zigpos.de/docker-ci:2021.1
  tags:
    - docker
  before_script:
    - export DOCKER_BUILDKIT=1
    - 'BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
    - 'VERSION=${CI_COMMIT_REF_NAME//release-/""}'
    - 'IMAGE_NAME="$DOCKER_REGISTRY/$REPO_GROUP"-amd64'
    - "ARCH=$(uname -m)"
  script:
    - "echo Build+Push $IMAGE_NAME for $ARCH"
    - 'docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"'
    - 'docker build --build-arg BUILD_DATE=$BUILD_DATE --build-arg VERSION=$VERSION -t "$IMAGE_NAME" .'
    - 'docker push "$IMAGE_NAME"'
  only:
    - /^release-.*$/

