stages:
  - docker

variables:
  DOCKER_REGISTRY: "docker.zigpos.de"
  REPO_GROUP: "zpBluetoothClassicScanner"
  DOCKER_CLI_EXPERIMENTAL: "enabled"

build raspi docker image:
  image: docker.zigpos.de/docker-ci-arm64
  tags:
    - docker-arm64
  services:
    - docker.zigpos.de/dind-ci-service-arm64
  stage: docker
  script:
    - 'cd DB-Docker'
    - 'BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
    - 'COMMIT_REF_NAME=$CI_COMMIT_REF_NAME'
    - 'VERSION=${COMMIT_REF_NAME//release-/""}${DOCKER_TAG_SUFFIX}'
    - 'IMAGE_NAME="$DOCKER_REGISTRY/$REPO_GROUP:$VERSION"'
    - 'echo $IMAGE_NAME'
    - 'docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"'
    - 'docker build --build-arg BUILD_DATE=$BUILD_DATE --build-arg VERSION=$VERSION -t "$IMAGE_NAME"-arm64 .'
    - 'docker push "$IMAGE_NAME"-arm64'
  only:
    - /^release-.*$/
    - /^prerelease-.*$/