stages:
  - deploy

variables:
  DOCKER_REGISTRY: "hub.zigpos.com"
  REPO_GROUP: "zp-grafana"
  DOCKER_CLI_EXPERIMENTAL: "enabled"

Docker (pre-)release arm64:
  stage: deploy
  image: hub.zigpos.com/ci/docker-ci:2022.1
  tags:
    - docker-arm64
  #services:
  #  - hub.zigpos.com/dind-ci-service-arm64
  script:
    - 'BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
    - 'COMMIT_REF_NAME=$CI_COMMIT_REF_NAME'
    - 'VERSION=${COMMIT_REF_NAME##release-}'
    - 'IMAGE_NAME="$DOCKER_HUB_DEV_REPOSITORY/$REPO_GROUP:$VERSION"'
    - 'echo $IMAGE_NAME'
    - 'docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD" "$DOCKER_HUB_REPOSITORY"'
    - 'docker build --build-arg BUILD_DATE=$BUILD_DATE --build-arg "GF_INSTALL_IMAGE_RENDERER_PLUGIN=true" --build-arg VERSION=$VERSION -t "$IMAGE_NAME"-arm64 .'
    - 'docker push "$IMAGE_NAME"-arm64'
  only:
    - /^release-.*$/
    - /^prerelease-.*$/