stages:
  - containerize

variables:
  DOCKER_REGISTRY: "hub.zigpos.com/dev"
  REPO_GROUP: "zp_bt_scanner"
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  VERSION: 0.0.1

Docker release arm64:
  stage: containerize
  image: hub.zigpos.com/ci/docker-ci:2022.1
  tags:
    - docker-arm64
  script:
    - "echo otha"
    - export DOCKER_BUILDKIT=1
    - 'BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
    - 'COMMIT_REF_NAME=$CI_COMMIT_REF_NAME'
    - 'VERSION=${COMMIT_REF_NAME##release-}'
    - 'IMAGE_NAME="$DOCKER_HUB_DEV_REPOSITORY/$REPO_GROUP:$VERSION"'
    - 'echo $IMAGE_NAME'
    - 'docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD" "$DOCKER_HUB_REPOSITORY"'
    - 'docker build --build-arg BUILD_DATE=$BUILD_DATE --build-arg "GF_INSTALL_IMAGE_RENDERER_PLUGIN=true" --build-arg VERSION=$VERSION -t "$IMAGE_NAME"-arm64 .'
    - 'docker push "$IMAGE_NAME"-arm64'

  only:
    - /^release-.*$/
    - /^prerelease-.*$/
