stages:
  - containerize

variables:
  DOCKER_REGISTRY: "hub.zigpos.com/dev"
  REPO_GROUP: "zp_bt_scanner"
  DOCKER_CLI_EXPERIMENTAL: "enabled"

Docker release arm64:
  stage: containerize
  image: hub.zigpos.com/ci/docker-ci:2022.1
  tags:
    - docker-arm64
  script:
    - "echo otha"
    - export DOCKER_BUILDKIT=1
    - 'BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
    - 'VERSION=${CI_COMMIT_REF_NAME//release-/""}'
    - 'echo "Releasing Version "$VERSION'
    - 'IMAGE_NAME="$DOCKER_HUB_DEV_REPOSITORY/$REPO_GROUP:$VERSION"'
    - "ARCH=$(uname -m)"
    - "echo Build+Push $IMAGE_NAME for $ARCH"
    - 'docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD" "$DOCKER_REGISTRY"'
    - 'docker build --build-arg BUILD_DATE=$BUILD_DATE --build-arg VERSION=$VERSION -t "$IMAGE_NAME" .'
    - 'docker push "$IMAGE_NAME"'



